### ISSUE TITLE
Getting Java version is failing with path which contains '(' or ')'

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1066]
I some cases where path to user folder on Windows has brackets it is failing to get Java version. Following path: 
`C:\Users\ZarzyckiPiotr(CW)\`

Causes error:

`"Java version full information: 'C:\Users\ZarzyckiPiotr' is not recognized as an internal or external command"`

**Comment by Igazine** [comment]
I had a hunch yesterday it's a path (character) related issue. Putting this part of the command in quotes should probably fix it immediately.

**Comment by piotrzarzycki21** [comment]
> I had a hunch yesterday it's a path (character) related issue. Putting this part of the command in quotes should probably fix it immediately.
> 
> `C:\Users\ZarzyckiPiotr(CW)\`
> 
> should be
> 
> `"C:\Users\ZarzyckiPiotr(CW)\"`

It was good hunch @Igazine ! Thank you!

Everything is happening in this callback function:

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/9510be4cb9c42ebef4433b62a3e6a22db1b1ea2c/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/ActionScriptLanguageServerManager.as#L359

We are getting value which contains NativeProcess arguments, so probably fix should go inside:

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/9510be4cb9c42ebef4433b62a3e6a22db1b1ea2c/ide/MoonshineDESKTOPevolved/src/actionScripts/utils/EnvironmentSetupUtils.as#L86

With that part I believe is more familiar @rat-moonshine .

**Comment by JoelProminic** [comment]
Yeah, it seems like another issue with not escaping the path properly.

@piotrzarzycki21, as a local workaround, you could try creating a [symlink](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) for the Java path.  This would look somehting like:

    mklink /D C:\JavaSymlink "C:\Users\ZarzyckiPiotr(CW)\"

You'll need to manually enter the path in the Moonshine filechoser - the symlink is converted to the real directory when browsing normally.

**Comment by JoelProminic** [comment]
I did a quick test on Windows 11 with symlinks to see if I could reproduce your error, but I found that Moonshine seemed to convert to the original path before running any commands.

Then I tried to reproduce @piotrzarzycki21's errors by renaming `C:\MoonshineSDKs\Java` to `C:\MoonshineSDKs\Java(original)`.  However, I could not get this set properly in Moonshine:
1. Moonshine > Settings > Default SDKs
2. Change JDK 11 to the new path
3. Save the settings
4. Reopen the settings.  BUG:  the JDK 11 path shows as "Not Set"

I tried setting the `JAVA_HOME` environment variable instead, but in this case Moonshine set the JDK paths to the default values, with errors showing that the paths were invalid.  This may be a separate issue that we need to investigate.

@piotrzarzycki21, do you remember how you setup this JDK?  Also, please clarify which features have this error. I think you have mentioned it for the language server for Flex or Royale, and the About page.   Are you seeing a similar error when building Flex or Java projects?

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21, do you remember how you setup this JDK? Also, please clarify which features have this error. I think you have mentioned it for the language server for Flex or Royale, and the About page. Are you seeing a similar error when building Flex or Java projects?

Language server doesn't work - I have following error:

`Failed to load Java version. ActionScript & MXML code intelligence disabled for project: ....`

My path to Java is `C:\MoonshineSDKs\Java\java10` - I don't remember now what is correct java directory in my case on Windows - I will check tomorrow. I have no idea why path mentioned in the issue is in play while checking Java version.

**Comment by piotrzarzycki21** [comment]
I think [Native process argument](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/9510be4cb9c42ebef4433b62a3e6a22db1b1ea2c/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/ActionScriptLanguageServerManager.as#L378) value contains more than path to Java, but also contains several other paths and it's just failing on the one which I have mention.

**Comment by JoelProminic** [comment]
Ah, I see I misunderstood - I thought the path from the description was the beginning of the Java path, but it was actually the user home directory.

I don't immediately remember any environment variables that use the user home directory.  I remember that we specifically avoided putting MoonshineSDKs in the Home directory for Windows to avoid problems with remote directories (#478).

On that note, I remember that we had warnings on the console when running Moonshine from a remote directory:  #707.   However, this case did not prevent Moonshine from running.

In any case, I think it is worth checking if your home directory is a remote directory.  You can check this by opening the directory, right-clicking and choosing "Properties", and checking for a path like `\\domain.com\...` in the General tab.

**Comment by piotrzarzycki21** [comment]
> I don't immediately remember any environment variables that use the user home directory. I remember that we specifically avoided putting MoonshineSDKs in the Home directory for Windows to avoid problems with remote directories (#478).

MoonshineSDKs is not in my Home directory (if you consider Home directory as `C:\Users\ZarzyckiPiotr(CW)\`. That folder is in `C:\MoonshineSDKs`

**Comment by piotrzarzycki21** [comment]
> In any case, I think it is worth checking if your home directory is a remote directory. You can check this by opening the directory, right-clicking and choosing "Properties", and checking for a path like `\\domain.com\...` in the General tab.

It doesn't look it is. I see in Location section of General tab "C:\Users" - I went into properties of folder `C:\Users\ZarzyckiPiotr(CW)\`

**Comment by piotrzarzycki21** [comment]
What more information is needed in order to fix that ? I think someone has to go with breaking point [here](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/9510be4cb9c42ebef4433b62a3e6a22db1b1ea2c/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/ActionScriptLanguageServerManager.as#L359). Next check what value is inside "value" property - if it contains your user home (doesn't matter what it will be `C:\Users\{yourusername}`) that's the place which should be taken care of, cause in my case this is what probably causes whole mess.

**Comment by rat-moonshine** [comment]
- Moonshine > Settings > Default SDKs
- Change JDK 11 to the new path having "(", ")" parenthesis 
- Save the settings
- Restart Moonshine and open Settings. BUG: the JDK 11 path shows as "Not Set"

This [report](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1066#issuecomment-1191848866) from @JoelProminic should be fixed now.

Moonshine saves its temporary variables as a batch file on Windows, along with different other paths. This looks something like this (Note, I renamed the Java directory with parenthesis):

```
@echo off
set FLEX_HOME=C:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0
set JAVA_HOME=C:\MoonshineSDKs\Java\open(jdk)-11.0.10
...
set PATH=%FLEX_HOME%\bin;%JAVA_HOME%\bin;....;%PATH%
```
I don't see we require any change to these generation. However, there's another command runs by Java language servers targeting JDK path and write into that batch file, did required an encoding. I fixed that, and I confirm language server started work again for me. I tested with ActionScript language server but I also applied the fix in other language server class files.

For a test, I print the Java path on console:
![image](https://user-images.githubusercontent.com/24370870/180439963-211bc532-f73b-4e40-86df-c39d0c807dc4.png)

Where it creates trouble when a system user name has parenthesis, I don't have a position to test this. But as I have shown above, the environment variable paths has no reference to user-name. Unless there is a custom SDK path like `C:\Users\$user\Desktop\$sdk`.

Give this try with the fix, I didn't noticed any language server break anymore when JDK path has parenthesis.

**Comment by piotrzarzycki21** [comment]
Thanks @rat-moonshine ! Can you check if bamboo win build is working ?

**Comment by JoelProminic** [comment]
The Windows build broke on an unrelated SVN error.  I am retrying it now.

**Comment by JoelProminic** [comment]
The build (1112) is finished now.  I did some quick tests with a Java path with parenthesis, and that worked fine.

@piotrzarzycki21, if you still have trouble, check the exported environment script in `C:\Users\$User\AppData\Local\Temp\moonshine\environmental` for any references to your home directory.

**Comment by piotrzarzycki21** [comment]
> * Moonshine > Settings > Default SDKs
> * Change JDK 11 to the new path having "(", ")" parenthesis
> * Save the settings
> * Restart Moonshine and open Settings. BUG: the JDK 11 path shows as "Not Set"
> 
> This above bug [report](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1066#issuecomment-1191848866) from @JoelProminic should be fixed now.
> 
> Moonshine saves its temporary variables as a batch file on Windows, along with different other paths. This looks something like this (Note, I renamed the Java directory with parenthesis):
> 
> ```
> @echo off
> set FLEX_HOME=C:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0
> set JAVA_HOME=C:\MoonshineSDKs\Java\open(jdk)-11.0.10
> ...
> set PATH=%FLEX_HOME%\bin;%JAVA_HOME%\bin;....;%PATH%
> ```
> 
> I don't see we require any change to these generation. However, there's another command runs by Java language servers targeting JDK path and write into that batch file, did required an encoding. I fixed that, and I confirm language server start to work again for me. I tested with ActionScript language server but I also applied the fix in other language server class files.
> 
> For a test, I print the Java path on console: ![image](https://user-images.githubusercontent.com/24370870/180439963-211bc532-f73b-4e40-86df-c39d0c807dc4.png)
> 
> Where it creates trouble when a system user name has parenthesis, I don't have a position to test this. But as I have shown above, the environment variable paths has no reference to user-name. Unless there is a custom SDK path like `C:\Users\$user\Desktop\$sdk`.
> 
> Give this try with the fix, I didn't noticed any language server break anymore when JDK path has parenthesis.

@rat-moonshine I just tested that and it is still failing. I will have to bring back [this commit](https://github.com/Moonshine-IDE/Moonshine-IDE/commit/9510be4cb9c42ebef4433b62a3e6a22db1b1ea2c) to see more details, but I'm assuming it same issue.
@JoelProminic I did look into path mentioned and I see several *.cmd scripts - most of them look similar, but one was a bit different:

```
@echo off
set ROYALE_HOME=C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.10-bin-js
set JAVA_HOME=C:\MoonshineSDKs\Java\openjdk-11.0.10
set ANT_HOME=c:\MoonshineSDKs\Ant\apache-ant-1.10.12
set MAVEN_HOME=c:\MoonshineSDKs\Maven\apache-maven-3.8.3
set PATH=%ROYALE_HOME%\bin;%JAVA_HOME%\bin;%ANT_HOME%\bin;%MAVEN_HOME%\bin;%PATH%
"%JAVA_HOME%\bin\java.exe" -version
```

Maybe it helps to have some clue.

**Comment by rat-moonshine** [comment]
> I did look into path mentioned and I see several *.cmd scripts - most of them look similar, but one was a bit different:

This generally is the most expected script, I don't see you have any difference than us, here. 

However, when a language server starts, it also runs some command targeting the JDK path which I fixed with some encoding - and this fix the problem I or Joel encountered earlier, where JDK path had special characters:
`$jdkPath/bin/java.exe -Dfile.encoding=UTF8.....`

The above part generally adds to the batch file when a project opens or its associated language server starts. I also don't see any reference to your `Home` directory here.

**Comment by piotrzarzycki21** [comment]
I will push to master temporary code which prints arguments which we are trying to send to NativeProcess and if it won't contains any sensitive info - I will post it here.

**Comment by rat-moonshine** [comment]
Adjusting more into the local environment generation logic in Moonshine, Moonshine-IDE now encodes all the `SET` paths on Windows. Previously, it was using simple line-break to separate `SET` commands and without any encoding, that shown working so far. I chose to encode the paths anyway, this didn't shown any break in my immediate tests.

Let me know if anyone seen any sudden breaks now after the update.

While working on this I also able to fix a long waiting issue #741 .

**Comment by piotrzarzycki21** [comment]
No changes @rat-moonshine I'm still getting this issue. I can reproduce it when I go to Help -> About screen. 

`'C:\Users\ZarzyckiPiotr' is not recognized as an internal or external command, operable program or batch file.`

I just remind you that my user name is `C:\Users\ZarzyckiPiotr(CW)`. I think in order to reproduce this problem you should create on your windows user which has following name: "NameUsername(CW)" - which create for you following folder `C:\Users\NameUsername(CW)` - Log in to that user, install Moonshine and try to reproduce issue. @Aszusz soon on his virtual machine try to create that user, so he may let us know whether it is possible.

**Comment by Aszusz** [comment]
> @Aszusz soon on his virtual machine try to create that user, so he may let us know whether it is possible.

Yes, I was able to create a user with this name and home dir in a standard windows way on Win 10.

**Comment by Aszusz** [comment]
@rat-moonshine 
I created VirtualMachine with Pete's username and was able to reproduce this issue:

```
: Java version environment values: C:\Users\ZarzyckiPiotr(CW)\AppData\Local\Temp\moonshine\environmental\2C81B94F-7CC2-6FF5-B0EA-35F49CC47E99.cmd
: Java version full information: 'C:\Users\ZarzyckiPiotr' is not recognized as an internal or external command,
: operable program or batch file.
: Failed to load Java version. ActionScript & MXML code intelligence disabled for project: NewJavaScriptBrowserProject. Exit code: 1
```

**Comment by JoelProminic** [comment]
From this, it looks like the bug is that the environment variable path is not escaped.  However, I would have expected this to trigger an error on any action where the environment was set (which should be basically any command). Do we have different code to run the environment variable script for Java?

**Comment by rat-moonshine** [comment]
I commit a small fix where encoding the batch path before running. Please give this a test, and let me know if this fix the problem.

**Comment by Aszusz** [comment]
Testing this build, the output seems a little worrying:
```
: The system cannot find the path specified.
: Java version environment values: ^C^:^\^U^s^e^r^s^\^Z^a^r^z^y^c^k^i^P^i^o^t^r^(^C^W^)^\^A^p^p^D^a^t^a^\^L^o^c^a^l^\^T^e^m^p^\^m^o^o^n^s^h^i^n^e^\^e^n^v^i^r^o^n^m^e^n^t^a^l^\^2^F^8^2^0^B^8^F^-^3^B^F^8^-^1^1^D^0^-^D^4^F^6^-^3^6^4^A^A^3^2^C^7^5^B^2^.^c^m^d
: Java version full information: openjdk version "11.0.10" 2021-01-19
: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
But Java path is recognized properly, the project is building and the language server is working.

**Comment by JoelProminic** [comment]
I created a test user on my Windows Vagrant instance, and it looks like this problem is more widespread.  Some other features that are affected:
- The versions on the About page are not populated.
- Auto-update does not open the installer after Moonshine is closed (the installer is downloaded to a temp location under the user directory)

![image](https://user-images.githubusercontent.com/24532731/180834262-743023df-586d-441e-9db8-52cfadf1e7ad.png)


I tested @rat-moonshine's update, and this fixes the language server and About page problems.  We'll need to do more testing an review to confirm if there are other features that need to be fixed.

**Comment by Aszusz** [comment]
I also confirm @JoelProminic findings:
- auto updates are unusable
- sdk installer needs to be downloaded and started manually
- some sdks don't install correctly

But before we jump onto fixing all these issues let's consider if it's even worth it. If a user has special characters in his/hers home directory path broken Moonshine may be the least important of the problems. I've seen A LOT of software breaking in unexpected places when the path contains parentheses and Git is a prime example of this.
Special characters in paths will break things all around Moonshine. Let's focus on the things @piotrzarzycki21 considers essential for his development.

**Comment by JoelProminic** [comment]
@Aszusz, since the fix is easy, I think it is worth briefly looking for other obvious features that may have issues related to not escaping the home directory.  The parenthesis or special character case may not be common, but I suspect this will trigger on spaces as well (I'll test when I have a chance).   We should focus our attention on features that use temporary files.  I tried:
- FormBuilder:  Project > Generate Java Agents  (did not trigger)
- Settings > Templating > Modify (did not trigger)
- Tour De Flex examples (did not trigger)

It looks like you were concerned about this line in the output:

    : Java version environment values: ^C^:^\^U^s^e^r^s^\^Z^a^r^z^y^c^k^i^P^i^o^t^r^(^C^W^)^\^A^p^p^D^a^t^a^\^L^o^c^a^l^\^T^e^m^p^\^m^o^o^n^s^h^i^n^e^\^e^n^v^i^r^o^n^m^e^n^t^a^l^\^2^F^8^2^0^B^8^F^-^3^B^F^8^-^1^1^D^0^-^D^4^F^6^-^3^6^4^A^A^3^2^C^7^5^B^2^.^c^m^d

This is our robust/overkill method for escaping the paths.  We could be smarter with this logic (i.e. not escaping alphanumeric characters), but this path shouldn't be displayed normally.  I figure it is probably not worth rewriting and retesting this escape logic for now, but we can revisit it if it becomes a problem.

**Comment by rat-moonshine** [comment]
@Aszusz Can you elaborate the behaviour about [this](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1066#issuecomment-1194377329) observation:

> sdk installer needs to be downloaded and started manually

**Comment by Aszusz** [comment]
> @Aszusz Can you elaborate the behaviour about this observation:

Sure. It looks like I also made a mistake and the sdk instller needs to be donwloaded manually but not started. Here's exactly what happend for me:
- I downloaded and opened Moonshine IDE. Getting Started page opened
- I clicked on the Download Third-Party Software but the download of SDK Installer didn't start or didn't succeed. I didn't get the installation prompt. I clikced a couple of times and eventually went to the webpage and downloaded it manually. But I downloaded the development version.
- With Moonshine SDK installer development version installed each time I cliked on the Download Third Party Software button the download process tried to start (because there was no release version installed) so I simply started it manually and installed the SDKs I needed.
- Now I downloaded SDK Installer 4.3.0 stable and when I click on the Download Third Party Software button it starts correctly.

So there's just a one bug, during the download or shortly after. Starting works correctly.

**Comment by piotrzarzycki21** [comment]
> Testing this build, the output seems a little worrying:
> 
> ```
> : The system cannot find the path specified.
> : Java version environment values: ^C^:^\^U^s^e^r^s^\^Z^a^r^z^y^c^k^i^P^i^o^t^r^(^C^W^)^\^A^p^p^D^a^t^a^\^L^o^c^a^l^\^T^e^m^p^\^m^o^o^n^s^h^i^n^e^\^e^n^v^i^r^o^n^m^e^n^t^a^l^\^2^F^8^2^0^B^8^F^-^3^B^F^8^-^1^1^D^0^-^D^4^F^6^-^3^6^4^A^A^3^2^C^7^5^B^2^.^c^m^d
> : Java version full information: openjdk version "11.0.10" 2021-01-19
> : OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
> : OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
> ```
> 
> But Java path is recognized properly, the project is building and the language server is working.

@rat-moonshine @Aszusz This output is temporary. I have placed it there in order do discover where we have this issue. I will remove that output.

**Comment by piotrzarzycki21** [comment]
> * Auto-update does not open the installer after Moonshine is closed (the installer is downloaded to a temp location under the user directory)

I'm experiencing that one as well on my machine.

**Comment by piotrzarzycki21** [comment]
I just tested it:
- Original issue has been fixed - Language server is starting for me and working properly
- About page is working properly as well
- Installer update will be tested soon.

**Comment by rat-moonshine** [comment]
> > * Auto-update does not open the installer after Moonshine is closed (the installer is downloaded to a temp location under the user directory)
> 
> I'm experiencing that one as well on my machine. However I will do tests whether fix from @rat-moonshine help here.

This shall be fix with my next commit. The test output will also be removed from the console.

**Comment by rat-moonshine** [comment]
> I clicked on the Download Third-Party Software but the download of SDK Installer didn't start or didn't succeed. I didn't get the installation prompt. I clikced a couple of times and eventually went to the webpage and downloaded it manually. But I downloaded the development version.

@Aszusz I need some more help to pin-point the problem here. Do you remember, or can re-test and suggest on the following?

1. After clicking on "Download Third-Party Software", a message appears beneath the button saying _Moonshine SDK Installer is downloading. Please wait_?
2. If appears, is it disappears as well after some time?

**Comment by Aszusz** [comment]
@rat-moonshine 
Yes, the message appears and stays for about 2 seconds.

**Comment by rat-moonshine** [comment]
> Yes, the message appears and stays for about 2 seconds.

Okay. It sounds like it maybe failing on default `File.openWithDefaultApplication()` run on Windows. I have changed the way to trigger, please give this a test.

Other updates:
- Auto-updater installer path encoded during a trigger
- Removed test message in console

**Comment by Aszusz** [comment]
If there is no SDK Installer present I can now click on the DTPS button and the installer of SDK Installer launches correctly.
But if the Installer is already present the button doesn't open it, but throws this error:
```
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at actionScripts.ui.feathersWrapper.help::GettingStartedViewWrapper/onDownload3rdPartySoftware()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at moonshine.plugin.help.view::GettingStartedView/onDownload3rdPatySoftware()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
: 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
```
I'll test auto-update with the next build.

**Comment by rat-moonshine** [comment]
I confirm the error. I'm checking.

**Comment by rat-moonshine** [comment]
This problem should resolve now, please test with latest build. 

While testing the section on macOS, Moonshine tries to access MSDKI download website (when it's not installed) but the website is inaccessible - https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/macOScripts/SendToASH.sh#L10.

**Comment by JoelProminic** [comment]
FYI, I did a test with the build from yesterday for a user with spaces in the name (Test User).  I could not reproduce the auto-update or MSDKI errors, so it seems that this bug does not trigger with spaces only.   I'll do more tests with special characters once the new builds completes.

**Comment by Aszusz** [comment]
@rat-moonshine 
Automatic updates work.
SDK Installer dwonloads and opens correctly.
Also, I fixed the website.

@JoelProminic 
I think this triggers only for parenthesis. What's your home direcetory path `C:\Users\Test User\` or `C:\Users\Test\`?

**Comment by JoelProminic** [comment]
The home directory for my "Test Space" user is `C:\Users\Test Space`.

I did some tests with the special character user, and I see that auto-updates and MSDKI are working now.

**Comment by piotrzarzycki21** [comment]
I just tested very last thing on my machine - Automatic update - It's working fine. Adrian did additional tests as well.
