### ISSUE TITLE
Flex or Royale UI Based CRUD on Tabular Interface

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#704]
Now that we have the Tabular Interface (#670) working for generating a Domino Database, we would like to explore generating other parts of the UI.  In order to have a working UI, we would need:
- The backend database.  This is done with #670 
- CRUD agents.   This will probably be implemented with #668 
- UI code to call the agents, parse the data, and generate a CRUD UI.

Since we have the field names and types already, we should be able to implement basic CRUD logic (no custom field behavior or validation) based on the field list.

---------------------------------------------------------------

(Updated by @rat-moonshine )
After a discussion with @JoelProminic here's the extended plan for this as follows:

**Initial Goal:**
- [x] CRUD project generation option should be under the 'Projects' menu and applicable for the entire OnDisk project
- [x] Generation of CRUD project should consist of all the available .dfb files and not any particular
- [x] Royale template needs to have a dashboard/home screen where user can choose to which .dfb module they want to load
- [x] Each .dfb module in the CRUD project requires to have their own set of listing, add/edit views and corresponding agent calls, as they going to be very separated between each module
- [ ] Respective web-service calls in individual modules

**Phase 2 Goal:**
- [ ] User can open any Royale application in Moonshine, and choose to generate any particular .dfb or complete OnDisk project's CRUD class-files to the Royale application, probably through a context-menu in its file-tree

**Comment by rat-moonshine** [comment]
Here are some initial thoughts for brainstorming. 

The proposed Royale application I'm envisioning a very basic structured one without having any dependency to any particular framework (i.e. PureMVC etc.), so an user need not to have knowledge of particular framework and operate. 

Some questions as raised,

1. Do we want the user to take the Royale project files and proceed for self-build?
2. Do we have a requirement to run the project in IIS environment only? (I guess probably we need)
3. Does the CRUD application requires any authentication behavior to access the Domino agents?

As I discussed this with @JoelProminic we both agreed we possibly needs a template-driven approach for the CRUD application. The template files will be part of a Royale application (which we can bundle within the Moonshine-IDE) and we needs to update its particular section based on the Tabular-interface data. 

As I was thinking the approach on CRUD project generation, we could proceed with two separate options:

1. **Straightforward:** The Royale project will generates every time with corresponding Tabular-interface information and saved to disk-location. The disadvantage of this design is any existing project files in target location may overwrite unless user intentionally do so, or needs to choose another location. User may needs to build the project by self again and deploy to IIS to test.
2. *Config-driven:* We could think for a design where the Royale application project will hold static code and it'll run on an external configuration file. Moonshine-IDE will generate/update this external configuration file, the Royale application will responsible to read/parse this file and generate its UI etc. The advantage of this design is, upon any modification in Tabular-interface user may not need to build the CRUD project again. S/he can only copy the configuration file to IIS and test. At Moonshine side, the template files will remain untouched but only generates a configuration XML. One disadvantage of this design is if we made any structural changes to the Royale application in future, we need to make sure user build the project again.

@JoelProminic , @piotrzarzycki21 , let me know yours thought on this.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Even without going to deep into above plan - the one thing is obvious - we would like to have simple Royale application which is able to do CRUD to Domino. I'm strongly suggesting you to start from that point instead do anything in Moonshine in the first place. 

- [ ] Create first Royale application which contains everything what we need - Don't spend too much time on the code - attach it here and I will review it, simplify it for you etc. 
- [ ] Next you will focus on how that application should connect with domino in a Simple and efficient way - I will assist here as well
- [ ] I will add code documentation so user could understand app inside 

In my opinion this should be first 3 steps. Thoughts ?

**Comment by rat-moonshine** [comment]
Sounds fine, @piotrzarzycki21 . In any way, we need to start with Royale application first so we can see what basic requirements it needs from Moonshine-IDE to work. Do you have any simple, clean-up project already at your disposal using basic server connections to use with? We probably require CORS bead in the project as well.

We can continue to tune-up the Royale template while in the separate branch. 

On two separate procedures to generate CRUD application, I discussed this with @JoelProminic  and he's pointed out one crucial thing that a config-driven approach may make things difficult for the user who wants to further modify the application per their needs. So we probably going to stick with 'straightforward' generation ways for now.

**Comment by piotrzarzycki21** [comment]
> Do you have any simple, clean-up project already at your disposal using basic server connections to use with?

No I don't have such example. Create new Jewel project in Moonshine. Adjust it to have displaying what you need. Attach it here and I will make it simpler.

Next figure out how would you connect to created domino database from Flex - Maybe make example in Flex.

**Comment by rat-moonshine** [comment]
Any update on finalizing the template @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
Today in Poland are national vacation. I will have update on that tomorrow.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I don't understand why you have done that example so complicated :) You were suppose to create new project in Moonshine and start working from there. 
I have simplify this to Hello World - now it's your job add what we need - Once you finish attach it - I will look into it and probably make it even simpler. Look into MainContent.mxml there is a comment for you.
[RoyaleTabularCRUDTemplate.zip](https://github.com/prominic/Moonshine-IDE/files/4769299/RoyaleTabularCRUDTemplate.zip)

**Comment by rat-moonshine** [comment]
The project that you sent is most likely the example project we distribute from Moonshine for Royale (?) The project that I sent you have created using the same template only.

The project I sent is also what we mainly need. It consists of two different views - listing and add/edit, to support CRUD functionality. If you see the project that I sent, contains all the relevant sections/elements which you asked to add again into the blank project you sent. You're actually asking me to do the same thing again.  

You should look into the project I sent because I already attached what we need for a start, and simply it, based on the minimum we need.

**Comment by piotrzarzycki21** [comment]
> The project I sent also has what we need for now. It consists of two different views - listing and add/edit, to support CRUD functionality. If you see the project that I sent, contains all the relevant sections/elements which you asked to add again into the blank project you sent. You're actually asking me to do the same thing again.
> 
> You should look into the project I sent because I already added what we need for a start, and simply it, based on the minimum we need.

Ok let me look into that more and make it simpler. I will preserve ADD/Edit etc. stuff.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Here you have simpler version. I think it can be simpler, but it's a start. 
[RoyaleTabularCRUDTemplate.zip](https://github.com/prominic/Moonshine-IDE/files/4770023/RoyaleTabularCRUDTemplate.zip)

**Comment by rat-moonshine** [comment]
Thanks @piotrzarzycki21 . Let's start with this.

**Comment by rat-moonshine** [comment]
I'm having some UI issue in the updated project, can you take a look into @piotrzarzycki21 ?

The body content does not stretch to take the full-width:
![image](https://user-images.githubusercontent.com/24370870/84498051-82be3c80-accd-11ea-990a-d33b9b2a11b6.png)

I see the following element has a 50% width set but changing it didn't affect (in MainContent.mxml):
```
<listing:ItemsListing eventNavigateTo="onNavigationChangeRequest(event)" 
							percentWidth="50"/>
```

**Comment by piotrzarzycki21** [comment]
> I'm having some UI issue in the updated project, can you take a look into @piotrzarzycki21 ?
> 
> The body content does not stretch to take the full-width:
> ![image](https://user-images.githubusercontent.com/24370870/84498051-82be3c80-accd-11ea-990a-d33b9b2a11b6.png)
> 
> I see the following element has a 50% width set but changing it didn't affect (in MainContent.mxml):
> 
> ```
> <listing:ItemsListing eventNavigateTo="onNavigationChangeRequest(event)" 
> 							percentWidth="50"/>
> ```

Should stretch ? Is it requirements ? This is the simplest version where everything looks fine. Some more options need more CSS stuff - I would like to avoid that.

**Comment by rat-moonshine** [comment]
No, we want this to be 100% width. There could be many number columns in the actual project, so it's better to keep things 100% width as we can see in general HTML.

**Comment by piotrzarzycki21** [comment]
> No, we want this to be 100% width. There could be many number columns in the actual project, so it's better to keep things 100% width as we can see in general HTML.

Ok I will try to adjust it and provide you new version, but rather not today. You can remove precentWidth for ItemsListing and remove width completely without setting up anything from DataGrid.

**Comment by rat-moonshine** [comment]
Okay, I shall wait for an updated one.

**Comment by rat-moonshine** [comment]
Some generation-dependencies as suggested by @JoelProminic for my references,

> Most of the options should work the same way they do for the Domino form.
> Type and Multivalue will determine the control.
> Editable will determine if the field should be editable in the UI. I think we'll want the formula to be executed on the agent side only.
> Include in View, Sort Options - These fields should determine which fields appear in the main list, and the sorting to use.

Fields can be referred from here https://github.com/prominic/Moonshine-IDE/issues/670#issue-571561798.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/84878005-df8f6d80-b0a6-11ea-9dd4-313ccbf3dce4.png)

Recent changes in templates doesn't seem to use the full-width in the listing or add/edit section, yet. @piotrzarzycki21 please check.

**Comment by piotrzarzycki21** [comment]
> ![image](https://user-images.githubusercontent.com/24370870/84878005-df8f6d80-b0a6-11ea-9dd4-313ccbf3dce4.png)
> 
> Recent changes in templates doesn't seem to use the full page-width in the listing or add/edit section, yet. @piotrzarzycki21 please check.

Add percentWidth here:

```
<listing:ItemsListing eventNavigateTo="onNavigationChangeRequest(event)"
								  percentWidth="100"/>
```

Adding percentWidth to DataGrid may not work correctly - you can check, but I cannot promise you that all your columns will display as you wanted to.

**Comment by rat-moonshine** [comment]
> Adding percentWidth to DataGrid may not work correctly - you can check, but I cannot promise you that all your columns will display as you wanted to.

Adding percentWidth=100 doesn't make any change to the interface. I wonder why it's hard to have the interface 100% widthed. The interface also unredable (mainly Listing) when there are many columns. 

In the original template I proposed MyAccount like solution as here: https://github.com/prominic/MyAccount-Native-on-Royale/blob/master/src/net/prominic/mediator/correspondence/MediatorCorrespondenceBase.as#L137. This overcome the width-restriction problem. Do you think we can re-introduce this?

**Comment by piotrzarzycki21** [comment]
> Adding percentWidth=100 doesn't make any change to the interface. I wonder why it's hard to have the interface 100% widthed. The interface also unredable (mainly Listing) when there are many columns.

Weird. My interface is being stretch properly.

![stretch](https://user-images.githubusercontent.com/24554795/84881105-b44c5480-b08d-11ea-8541-72574fea5ca1.png)

Could you show me screenshot ? What browser are you using ?

**Comment by piotrzarzycki21** [comment]
> In the original template I proposed MyAccount like solution as here: https://github.com/prominic/MyAccount-Native-on-Royale/blob/master/src/net/prominic/mediator/correspondence/MediatorCorrespondenceBase.as#L137. This overcome the width-restriction problem. Do you think we can re-introduce this?

No we shouldn't reintroduce any kind of custom solution. This solution is based on calculating and adding to DataGrid fixed width. I will start again talk with Carlos about those issues soon. Simply either do not add any width to DataGrid, or add some fixed - maybe also would work adding fixed maxWidth - I'm not sure.

**Comment by rat-moonshine** [comment]
I give you the [screenshot](https://github.com/prominic/Moonshine-IDE/issues/704#issuecomment-645249259). Same in Chrome and Firefox. I can arrange a sharing if you prefer.

**Comment by piotrzarzycki21** [comment]
> I gave you the [screenshot](https://github.com/prominic/Moonshine-IDE/issues/704#issuecomment-645249259). Same in Chrome and Firefox. I can arrange a sharing if you prefer.

I have pushed to your branch percentWidth="100". Could you please run example and check in Chrome console that you have 100% set in Elements window ?

![stretch](https://user-images.githubusercontent.com/24554795/84904330-7d873600-b0af-11ea-956d-636705b995ad.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have prepared pom file for build. Take a look into template and check whether used [$ProjectName](https://github.com/prominic/Moonshine-IDE/blob/d640f0d1034bbd99a69ddaa80667992b66a17324/ide/MoonshineSharedCore/src/elements/templates/royaleTabularCRUD/project/pom.xml.template#L102) will be replaced after CRUD app is created.

**Comment by rat-moonshine** [comment]
After a discussion with @JoelProminic here's the extended plan for this as follows:

**Initial Goal:**
- [ ] CRUD project generation option should be under the 'Projects' menu and applicable for the entire OnDisk project
- [ ] Generation of CRUD project should consist of all the available .dfb files and not any particular
- [ ] Royale template needs to have a dashboard/home screen where user can choose to which .dfb module they want to load
- [ ] Each .dfb module in the CRUD project requires to have their own set of listing, add/edit views and corresponding agent calls, as they going to be very separated between each module

**Phase 2 Goal:**
- [ ] User can open any Royale application in Moonshine, and choose to generate any particular .dfb or complete OnDisk project's CRUD class-files to the Royale application, probably through a context-menu in its file-tree

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 can you see if you can update the [example](https://github.com/prominic/Moonshine-IDE/issues/704#issuecomment-643181684) template with Jodit editor integrated at some time?

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 can you see if you can update the template [example](https://github.com/prominic/Moonshine-IDE/issues/704#issuecomment-643181684) with Jodit editor integrated at some time?

Yes I can! I forgot it ! I will do that first thing in tomorrow morning.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 can you see if you can update the template [example](https://github.com/prominic/Moonshine-IDE/issues/704#issuecomment-643181684) with Jodit editor integrated at some time?

I cannot do too much in your code, cause I don't know logic behind adding item to the form. However I have pushed changes which prepares for you Jodit editor. Now you need to add logic which is responsible for displaying it would look like that:

1. Add import to Jodit class in view -> I have added it for you, so you won't have to generate https://github.com/prominic/Moonshine-IDE/commit/8f8db7da12e9276fe6ad3ebd835470da27388ba1
2. Add Jodit editor itself to view like that:

```
<joditeditor:JoditEditor localId="someId" percentWidth="100" toolbarVisible="true">					
</joditeditor:JoditEditor>
```

**Comment by rat-moonshine** [comment]
I cannot do too much in your code, cause I don't know logic behind adding item to the form. However I have pushed changes which prepares for you Jodit editor. Now you need to add logic which is responsible for displaying it would look like that:

Thanks!

Additionally, can you update the example project so we can use that time to time, to reference UI-integration/rapid-development process; I know the practical templating usage is not very straight-forward.

**Comment by piotrzarzycki21** [comment]
> Thanks!
> 
> Additionally, can you update the example project so we can use that time to time, to reference UI-integration/rapid-development process; I know the practical templating usage is not very straight-forward.

Generate for me current version of Project using your editor and attach here - I will change it. My example is a mess and if you generate it would be the most accurate.

**Comment by rat-moonshine** [comment]
> Generate for me current version of Project using your editor and attach here - I will change it. My example is a mess and if you generate it would be the most accurate.

Okay. I see that. I probably going to add one custom component too; I shall generate a reference project thereafter.

**Comment by rat-moonshine** [comment]
I have added a fixed datagrid-column width (200px) to overcome the readable-problem for now. The data-grid percentage sizing issue remains there, though.

**Comment by piotrzarzycki21** [comment]
> I have added a fixed datagrid-column width (200px) to overcome the readable-problem for now. The data-grid percentage sizing issue remains there, though.

Yep. Greg is going to work on that. The only thing which you can do is add fixed width for DataGrid for now.

**Comment by rat-moonshine** [comment]
Here's some quick referencing the progress we have so far:

1. Generation of CRUD project moves under "Project" menu
2. Unlike earlier implementation, the CRUD project now generates with all the available .dfb files (to an OnDisk project) - opened or non-opened to any editor
3. Moonshine ensures all the import statements, namespace statement generates properly in the Royale project
4. Royale project lands with a dashboard listing all the .dfb file modules
5. Every .dfb modules now have their own set of listing, add/edit-form and service implementations
6. Opening of Royale project after generation is automatic to Moonshine

Following are the normal and special form-field-types currently we're supporting:

1. Text input (normal and Number-only)
2. Date field 
3. Rich text (Jodit editor)
4. Multi-value list (Number-only and Date-only)

Following are a few visuals on how they currently look when running:

**Dashboard**
![image](https://user-images.githubusercontent.com/24370870/86998654-72b35300-c1ce-11ea-9544-ae9dc6d0ed8b.png)

**Inside each module**
![image](https://user-images.githubusercontent.com/24370870/86998692-89f24080-c1ce-11ea-9403-37d60ac2b033.png)![image](https://user-images.githubusercontent.com/24370870/86998992-3502fa00-c1cf-11ea-9c8a-de04e210fa4f.png)

**Comment by rat-moonshine** [comment]
While re-visiting this branch in need of https://github.com/Moonshine-IDE/Moonshine-IDE/issues/675#issuecomment-989037492, I updated the branch with `master`, fixed all the conflicts and start the application. 

Immediately, I fall in lost of memory problem and having difficulty to find where to generate the CRUD output. I think I able to find it however and able to generate an output Royale project. 

But with my surprise, I don't see ANY module information included in the generating Royale project that I described once here https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-655901058, anymore. 

At this point, I have no idea why it is this - why no module information included nor relevant files have generated. Based on the commit history I don't see I did any update since I last documented the progress-outputs. This a point of investigation now why it is broken. This may require me to dive in these long forgotten codes.

**Comment by rat-moonshine** [comment]
After spending hours I able to generate a more proper Royale project this time,
- Fixed errors and able to generate output with modules information
- Still some import statements are broken in generated project


Unfortunately, when I tried to commit my fix-changes along with last updates from `master` - the merge which produce a large number of files to commit (including files from LS/debug-servers), SourceTree is failing to commit:

![image](https://user-images.githubusercontent.com/24370870/145393202-76ab1b96-7fb8-4f8a-b971-fba1fa8da861.png)

Reading something over internet, it seems Git has a limit of commit arguments (4096) (https://jira.atlassian.com/browse/SRCTREE-693). It's already a huge file list to commit, and I'm currently stuck. 

@Aszusz do you see a way-out from this problem (?)

**Comment by JoelProminic** [comment]
@rat-moonshine was able to finish the commit using Moonshine and the `git` command.
https://github.com/Moonshine-IDE/Moonshine-IDE/commit/2acba9522b1762f1265bb2a78c8069b428f315eb
https://github.com/Moonshine-IDE/Moonshine-IDE/commit/49c3b544f4d50de7d89ebe8431fc97ba84d8281f

**Comment by rat-moonshine** [comment]
This maybe a separate case of discussion, but I noticed that Moonshine commit message do not respect line-breaks https://github.com/Moonshine-IDE/Moonshine-IDE/commit/2acba9522b1762f1265bb2a78c8069b428f315eb. However, the message field is does line breaks.

**Comment by rat-moonshine** [comment]
I have completed fix to generate correct Royale project output including all its required sources. I have also fixed the base template files which were generating [compilation error](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/675#issuecomment-970808097) noticed by @JoelProminic .

However, when this again generates correct Royale CRUD project, I see something is broken with Royale "Build/Run" probably since last day's merge from the `master`. 

Something is breaking during any Royale build/run using this branch build now:
```
: -js-output=/Users/devsena/Desktop/NewJavaScriptBrowserProject
: Internal error: java.lang.RuntimeException: Parameter 'closure-lib' doesn't point to a valid directory. org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:366)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:442)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:259)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:216)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:298)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:256)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:238)
: 4.761538913 seconds
```

I confirm if I take the generated Royale project to Development Moonshine build, I can able to compile and run successfully.

**Comment by rat-moonshine** [comment]
Hm, maybe something messed with my dev environment here; When I installed the branch build I don't see this error anymore.

**Comment by JoelProminic** [comment]
@rat-moonshine has the #704 branch working again here:  https://bamboo.prominic.net/browse/MS-BBMGO-41/artifact

Here is a process to test the issue:
1. Create a new Domino On Disk Project
2. Create and populate a couple .dfb files in `src/main/formbuilder` with Right Click > Form Builder DXL File
3. Project > Generate Apache Royale Project
4. Choose a parent directory in the filechooser
5. Change the custom SDK for the new project to Royale 0.9.9

Here are example projects:
[2021_12_10__TestOnDiskProject_1210.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/7695421/2021_12_10__TestOnDiskProject_1210.zip)

For each .dfb file, these files are generated:

    # Form
    src/views/modules/Author/AuthorViews/AuthorAddEdit.mxml
    # View
    src/views/modules/Author/AuthorViews/AuthorListing.mxml
    # Placeholders for storing data for the above interface and reading that data from a server
    src/views/modules/Author/AuthorServices/AuthorServices.as
    src/views/modules/Author/AuthorServices/AuthorProxy.as

In addition, the new interfaces are added in `src/views/general/Dashboard.mxml`

**Comment by JoelProminic** [comment]
@JustinProminic requested that we revisit this issue.   We would like to get what we have working merged into master, but we should set it up so that it can be easily disabled  for a production build if it is not in a usable state.   I think we would just need to disable the menu action.

**Comment by rat-moonshine** [comment]
**Requirement:**
1. Download Moonshine-IDE **_branch-build on macOS_** from Bamboo, for a test
2. Download/install `Apache Royale 0.9.9-SNAPSHOT` (Royale Nightly) SDK version using MSDKI if you don't have this already

Following are instruction to give this a test:
1. Download and install Moonshine-IDE branch build on macOS
3. Create a new **OnDisk** project
4. You can create as many modules or `.dfb` (short form of Domino Form Builder), for a tests I have created two modules:
![image](https://user-images.githubusercontent.com/24370870/155525097-3bfdf7d0-0836-459d-9487-61c1aeb17028.png)
(to create new `.dfb` file `right-click > Create > Form Builder DXL File`)
5. Double-click on the `.dfb` files and add some entries - each entry will correspond a column in Royale application's data-grid, and will be seen in module's add/edit form
6. Currently the `.dfb` form only supports following type of entries - Text, RichText, Date, Number
![image](https://user-images.githubusercontent.com/24370870/155526220-0cf49c34-1242-46ea-b67d-2b9ba18c927c.png)
7. Here I've created two modules named "Module A Title" and "Module B Title" with some entries in them:
![image](https://user-images.githubusercontent.com/24370870/155526430-96b067e3-ad67-48a1-a126-bfe85e0d5342.png)
8. Make sure to click on "Save & Generate DXL" to save your modules
9. Once ready to generate its Royale project, go to `Project > Generate Apache Royale Project`
![image](https://user-images.githubusercontent.com/24370870/155526582-8b11359b-bdf2-4f2f-963f-12b171f76bae.png)
10. Select the location to generate the Royale project in opening file-browser and select "Open"
11. This will generate a Royale project containing OnDisk inputs, and open in Moonshine-IDE:
![image](https://user-images.githubusercontent.com/24370870/155526821-40a7386e-0eb0-47a3-8956-5435a9ab9ed7.png)
12. Before running the Royale project, right-click on the project and open its settings
13. Go into `Build Options > Custom SDK`
14. Select `Apache Royale 0.9.9-SNAPSHOT` entry from the SDK list and chose "Select"
![image](https://user-images.githubusercontent.com/24370870/155527345-c0cc10ca-015c-4504-9888-cb1c7b0ba4c2.png)
15. Save the settings 
16. Build and run the Royale project by going into `Project > Build & Run`
17. After compilation is over the Royale project should open on a browser

Once ran on browser you should see a dashboard with module-named buttons - to go into respective modules:

![image](https://user-images.githubusercontent.com/24370870/155528985-0162c8dc-5a4e-4a1b-8180-fc5b1b63e1f6.png)

Inside each module you would see a data-grid (without any data now), a refresh button, and add-new button. Each data-grid columns are corresponding to every entry that being created in a `.dfb` file:

![image](https://user-images.githubusercontent.com/24370870/155529079-005ab1f1-3723-4cb4-8de1-c51411ca650a.png)

Opening the add-new form will also display each type of entry that being added in a `.dfb` file:

![image](https://user-images.githubusercontent.com/24370870/155529285-532b34f3-3d88-4ff0-992e-231acf91135b.png)

There is no data-binding in the populated Royale interface now, nor any data-model being created yet. 

Please, check.

**Comment by piotrzarzycki21** [comment]
> old data-grid component from Royale other than DevExpress one.

That's good and should stay like that in my opinion.

**Comment by JoelProminic** [comment]
The generated forms look good so far, but they won't submit without setting up the agents or in-memory model.  

For now, I think I would like to add a warning for the incomplete status and get this merged.  The warning should be displayed:
- On the home page (Available Modules)
- In a popup (or other error display) for the form Submit buttons

Use a message like:

> Form submission is currently disabled, and will be added with a future update.

We can create separate issues for generating the agents or creating an in-memory model.

@piotrzarzycki21 , do you have any objections to merging this with the current template?  I know you worked on a simpler template for #675.

**Comment by rat-moonshine** [comment]
> @piotrzarzycki21 , do you have any objections to merging this with the current template? I know you worked on a simpler template for https://github.com/Moonshine-IDE/Moonshine-IDE/issues/675.

If you want a quick check you can download the test-projects from [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-991288458). In the containing Zip file look into the project that named with `RoyaleApplication`.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 , do you have any objections to merging this with the current template? I know you worked on a simpler template for #675.

My template is completely different purpose. I'm trying to do not use in #675 template from this task - instead use for that simple one. I did changed some code in this area, but it shouldn't affect how template for this issue look like. You can go ahead and try to merge. I do expect conflicts no matter what.

**Comment by rat-moonshine** [comment]
I think let's not complicate this with the merge from #675 , and go with current [template](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-643181684) that is relevant for this purpose. This template is serving requisites for this particular implementation. 

We can have a review with @piotrzarzycki21 of generated project once we implemented the data-process mechanism to ensure if any place needs any improvement. 

I shall plan to have a merge meanwhile. I have added requisite [message](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-1050057028) suggested by @JoelProminic .

**Comment by piotrzarzycki21** [comment]
> I think let's not complicate this with the merge from #675 , and go with current [template](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-643181684) that is relevant for this purpose. This template is serving requisites for this particular implementation.
> 
> We can have a review with @piotrzarzycki21 of generated project once we implemented the data-process mechanism to ensure if any place needs any improvement.
> 
> I shall plan to have a merge meanwhile. I have added requisite [message](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/704#issuecomment-1050057028) suggested by @JoelProminic .

Merge this to master without touching my branch. Again my template is for different purposes. I have started to work on that cause it was using your template from #704 - which was simply wrong and shouldn't happen in the first place.

**Comment by rat-moonshine** [comment]
Yeah, I agree on that.

**Comment by rat-moonshine** [comment]
This issue is now merged into master.

**Comment by JoelProminic** [comment]
I need to test the "Include in View" updates.

@rat-moonshine reported that there were some remaining issues on the Royale side that he would like to review with @piotrzarzycki21 

Once we resolve the immediate problems we can close this issue.

**Comment by rat-moonshine** [comment]
I sent an email with details and generated project archive to @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
> I sent an email with details and generated project archive to @piotrzarzycki21 .

I think I will be able to look into that on Monday/Tuesday.

**Comment by JoelProminic** [comment]
@piotrzarzycki21 sent some suggested changes by email today.

**Comment by rat-moonshine** [comment]
The fix on multi-value list component from @piotrzarzycki21 is incorporated in template project. I confirm this fix the earlier multi-value list component problems.

Data-grid column still showing `[object object]` value for multi-value list properties. Since a fix to this also involves to fix variable-row-height first, it'd be good to get this fixed once we'll incorporate a better data-grid component like DevExpress.

**Comment by JoelProminic** [comment]
Pending changes, which may be moved to separate issue:
- DevExpress Datagrid
- Agents (#978)
